---
############################
# OS HARDENING (ALL HOSTS)
############################
- name: OS Hardening for Linux
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux (RedHat family only)
      selinux:
        state: disabled
      when: ansible_os_family == "RedHat"

    - name: Stop firewalld on RedHat
      service:
        name: firewalld
        state: stopped
        enabled: no
      when: ansible_os_family == "RedHat"
      ignore_errors: yes

    - name: Stop ufw on Debian
      service:
        name: ufw
        state: stopped
        enabled: no
      when: ansible_os_family == "Debian"
      ignore_errors: yes

############################
# BACKEND – NETDATA
############################
- name: Configure Backend (Netdata)
  hosts: backend
  become: yes
  tasks:
    - name: Install required packages
      package:
        name:
          - curl
          - bash
        state: present

    - name: Install Netdata if not installed
      command: bash -c "curl -fsSL https://get.netdata.cloud/kickstart.sh | bash -s -- --non-interactive"
      args:
        creates: /usr/sbin/netdata

    - name: Ensure Netdata runs on port 19999
      lineinfile:
        path: /etc/netdata/netdata.conf
        regexp: '^\s*default port ='
        line: '    default port = 19999'
      notify: Restart Netdata

  handlers:
    - name: Restart Netdata
      service:
        name: netdata
        state: restarted

############################
# FRONTEND – NGINX PROXY
############################
- name: Configure Frontend (Nginx Reverse Proxy)
  hosts: frontend
  become: yes
  vars:
    backend_ip: "{{ hostvars[groups['backend'][0]].ansible_host }}"

  tasks:
    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Write nginx.conf (OS-aware)
      copy:
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        content: |
          user {{ ansible_os_family == 'Debian' | ternary('www-data', 'nginx') }};
          worker_processes auto;
          error_log /var/log/nginx/error.log warn;
          pid /run/nginx.pid;

          events {
              worker_connections 1024;
          }

          http {
              include       /etc/nginx/mime.types;
              default_type  application/octet-stream;

              access_log /var/log/nginx/access.log;

              sendfile on;
              keepalive_timeout 65;

              include /etc/nginx/conf.d/*.conf;
          }

    - name: Write proxy configuration
      copy:
        dest: /etc/nginx/conf.d/proxy.conf
        mode: '0644'
        content: |
          server {
              listen 80 default_server;
              server_name _;

              location / {
                  proxy_pass http://{{ backend_ip }}:19999;
                  proxy_http_version 1.1;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Validate nginx configuration
      command: nginx -t
      changed_when: false

    - name: Start and enable nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
